export const DASHBOARD_HTML = [
  '<!DOCTYPE html>',
  '<html lang="fa" dir="rtl">',
  '<head>',
  '<meta charset="UTF-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '<title>Node Manager</title>',
  '<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">',
  '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.19.0/dist/tabler-icons.min.css">',
  '<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"><\/script>',
  '<style>',
  '*{margin:0;padding:0;box-sizing:border-box}',
  ':root{--bg:#0f081a;--bg2:#1a0e30;--bg3:#251040;--card:#160c28;--card-b:rgba(139,92,246,0.15);--accent:#8B5CF6;--accent2:#A78BFA;--accent-d:rgba(139,92,246,0.12);--green:#10B981;--green-bg:rgba(16,185,129,0.1);--green-t:#34D399;--red:#EF4444;--red-bg:rgba(239,68,68,0.1);--red-t:#F87171;--amber:#F59E0B;--amber-bg:rgba(245,158,11,0.1);--amber-t:#FCD34D;--t1:#F0E8FF;--t2:#9C8ABF;--t3:#6D4A9E;--sidebar-w:240px;--radius:16px}',
  '[data-theme="light"]{--bg:#F5F0FF;--bg2:#EBE0FF;--bg3:#DFD0FF;--card:#FFFFFF;--card-b:rgba(139,92,246,0.18);--accent:#7C3AED;--accent2:#6D28D9;--accent-d:rgba(124,58,237,0.08);--green:#059669;--green-bg:rgba(5,150,105,0.08);--green-t:#065F46;--red:#DC2626;--red-bg:rgba(220,38,38,0.08);--red-t:#A51E1E;--amber:#D97706;--amber-bg:rgba(217,119,6,0.08);--amber-t:#92400E;--t1:#1A0E30;--t2:#4A2D6E;--t3:#7A5DA6}',
  'html,body{height:100%}',
  'body{font-family:Vazirmatn,sans-serif;background:var(--bg);color:var(--t1);min-height:100vh;display:flex;font-size:14px}',
  '::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:var(--bg)}::-webkit-scrollbar-thumb{background:var(--bg3);border-radius:3px}',
  'a{color:inherit;text-decoration:none}',
  '.sidebar{width:var(--sidebar-w);min-height:100vh;background:var(--bg2);border-left:1px solid var(--card-b);display:flex;flex-direction:column;position:fixed;right:0;top:0;bottom:0;z-index:200}',
  '.logo{display:flex;align-items:center;gap:12px;padding:20px 16px 16px;border-bottom:1px solid var(--card-b)}',
  '.logo-icon{width:38px;height:38px;border-radius:50%;background:linear-gradient(135deg,#8B5CF6,#6D28D9);display:flex;align-items:center;justify-content:center;color:#fff;font-size:20px}',
  '.logo-name{font-size:13.5px;font-weight:700}',
  '.logo-sub{font-size:10px;color:var(--t3);margin-top:1px}',
  '.nav-wrap{flex:1;overflow-y:auto;padding:6px 0 8px}',
  '.nav-sec{padding:14px 14px 4px;font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:var(--t3);font-weight:700}',
  '.nav-it{display:flex;align-items:center;gap:9px;padding:9px 14px;color:var(--t3);font-size:12.5px;cursor:pointer;border-right:2px solid transparent;margin:1px 6px;border-radius:0 8px 8px 0}',
  '.nav-it i{font-size:16px;width:18px;text-align:center}',
  '.nav-it:hover{background:var(--accent-d);color:var(--t2)}',
  '.nav-it.on{background:var(--accent-d);color:var(--t1);border-right-color:var(--accent);font-weight:600}',
  '.sb-foot{padding:12px 14px;border-top:1px solid var(--card-b)}',
  '.theme-btn{display:flex;align-items:center;justify-content:center;gap:7px;background:var(--accent-d);color:var(--t2);border-radius:9px;padding:8px;font-size:12px;font-weight:500;font-family:inherit;border:1px solid var(--card-b);cursor:pointer;width:100%;margin-bottom:7px}',
  '.logout-btn{display:flex;align-items:center;justify-content:center;gap:7px;background:var(--red-bg);color:var(--red-t);border-radius:9px;padding:8px;font-size:12px;font-weight:500;font-family:inherit;border:1px solid rgba(239,68,68,0.2);cursor:pointer;width:100%}',
  '.main{margin-right:var(--sidebar-w);flex:1;padding:28px 28px 60px;min-width:0}',
  '.pg{display:none}.pg.on{display:block}',
  '.topbar{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:22px;flex-wrap:wrap;gap:12px}',
  '.tb-title{font-size:18px;font-weight:700;display:flex;align-items:center;gap:8px}',
  '.tb-title i{color:var(--accent);font-size:20px}',
  '.tb-sub{font-size:11px;color:var(--t3);margin-top:4px}',
  '.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin-bottom:18px}',
  '.metric{background:var(--card);border:1px solid var(--card-b);border-radius:var(--radius);padding:17px}',
  '.m-icon{width:34px;height:34px;border-radius:8px;background:var(--accent-d);display:flex;align-items:center;justify-content:center;margin-bottom:11px;color:var(--accent);font-size:17px}',
  '.m-label{font-size:10px;color:var(--t3);margin-bottom:4px;font-weight:600;text-transform:uppercase}',
  '.m-val{font-size:25px;font-weight:700;line-height:1}',
  '.m-unit{font-size:12px;font-weight:400;color:var(--t3)}',
  '.card{background:var(--card);border:1px solid var(--card-b);border-radius:var(--radius);padding:18px 20px;margin-bottom:16px}',
  '.card-title{font-size:12.5px;font-weight:700;margin-bottom:15px;display:flex;align-items:center;gap:7px}',
  '.card-title i{font-size:16px;color:var(--accent)}',
  '.btn{font-family:inherit;font-size:12px;font-weight:500;border-radius:9px;padding:8px 14px;cursor:pointer;display:inline-flex;align-items:center;gap:5px;border:none}',
  '.btn-p{background:linear-gradient(135deg,#8B5CF6,#6D28D9);color:#fff}',
  '.btn-sm{padding:5px 9px;font-size:10.5px}',
  '.fi,.fs{padding:9px 12px;border-radius:9px;border:1px solid var(--card-b);background:rgba(0,0,0,.18);color:var(--t1);font-family:inherit;font-size:12px;outline:none;min-width:100px}',
  '[data-theme="light"] .fi,[data-theme="light"] .fs{background:rgba(0,0,0,.04)}',
  '.badge{font-size:10px;padding:3px 10px;border-radius:20px;font-weight:700;display:inline-flex;align-items:center;gap:5px}',
  '.bg-green{background:var(--green-bg);color:var(--green-t)}',
  '.bg-blue{background:var(--accent-d);color:var(--accent2)}',
  '.bg-red{background:var(--red-bg);color:var(--red-t)}',
  '.bg-amber{background:var(--amber-bg);color:var(--amber-t)}',
  '.dot{width:6px;height:6px;border-radius:50%;display:inline-block}',
  '.dg{background:var(--green)}',
  '.empty{text-align:center;padding:50px 20px;color:var(--t3)}',
  '.empty i{font-size:40px;opacity:.3;margin-bottom:12px;display:block}',
  '.toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%) translateY(40px);background:var(--card);border:1px solid var(--card-b);color:var(--t1);border-radius:10px;padding:10px 18px;font-size:12.5px;opacity:0;transition:all .25s;z-index:999;pointer-events:none;box-shadow:0 4px 24px rgba(0,0,0,.45)}',
  '.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}',
  '.toast.ok{border-color:rgba(16,185,129,.3);background:var(--green-bg);color:var(--green-t)}',
  '.toast.err{border-color:rgba(239,68,68,.3);background:var(--red-bg);color:var(--red-t)}',
  '.row-item{background:var(--bg2);border:1px solid var(--card-b);border-radius:12px;padding:13px;margin-bottom:9px}',
  '.bar{height:4px;background:rgba(139,92,246,.1);border-radius:3px;overflow:hidden;margin-top:9px}',
  '.bar>div{height:100%}',
  '.ubar-txt{display:flex;justify-content:space-between;font-size:10px;color:var(--t3);margin-top:4px}',
  '.mono{font-family:ui-monospace,monospace;background:var(--accent-d);padding:2px 6px;border-radius:5px;cursor:pointer;font-size:10px}',
  '.chart-box{height:230px}',
  '@media(max-width:1050px){.sidebar{display:none}.main{margin-right:0}.metrics{grid-template-columns:1fr 1fr}}',
  '@media(max-width:500px){.metrics{grid-template-columns:1fr}.main{padding:20px 12px}}',
  '</style>',
  '</head>',
  '<body>',
  '<div class="toast" id="toast"></div>',
  '<aside class="sidebar">',
  '  <div class="logo">',
  '    <div class="logo-icon"><i class="ti ti-cube"></i></div>',
  '    <div><div class="logo-name">Node Manager</div><div class="logo-sub">v1.0 · Worker</div></div>',
  '  </div>',
  '  <div class="nav-wrap">',
  '    <div class="nav-sec">پنل</div>',
  '    <div class="nav-it on" data-pg="overview"><i class="ti ti-layout-dashboard"></i> داشبورد</div>',
  '    <div class="nav-it" data-pg="items"><i class="ti ti-folders"></i> پروفایل‌ها <span class="badge bg-blue" id="items-nb" style="margin-right:auto">0</span></div>',
  '    <div class="nav-it" data-pg="connections"><i class="ti ti-plug-connected"></i> اتصالات <span class="badge bg-blue" id="conns-nb" style="margin-right:auto">0</span></div>',
  '    <div class="nav-it" data-pg="logs"><i class="ti ti-history"></i> رویدادها</div>',
  '    <div class="nav-it" data-pg="errors"><i class="ti ti-alert-triangle"></i> خطاها</div>',
  '    <div class="nav-sec">سیستم</div>',
  '    <div class="nav-it" data-pg="settings"><i class="ti ti-settings"></i> تنظیمات</div>',
  '  </div>',
  '  <div class="sb-foot">',
  '    <button class="theme-btn" onclick="toggleTheme()"><i class="ti ti-moon" id="theme-icon"></i> <span id="theme-label">تم روشن</span></button>',
  '    <button class="logout-btn" id="logout-btn"><i class="ti ti-logout"></i> خروج</button>',
  '  </div>',
  '</aside>',
  '<main class="main">',
  '<section class="pg on" id="pg-overview">',
  '  <div class="topbar">',
  '    <div><div class="tb-title"><i class="ti ti-layout-dashboard"></i> داشبورد</div><div class="tb-sub" id="last-upd">در حال بارگذاری...</div></div>',
  '    <button class="btn btn-p btn-sm" onclick="refreshAll()"><i class="ti ti-refresh"></i> رفرش</button>',
  '  </div>',
  '  <div class="metrics">',
  '    <div class="metric"><div class="m-icon"><i class="ti ti-plug-connected"></i></div><div class="m-label">اتصالات فعال</div><div class="m-val" id="m-conns">—</div></div>',
  '    <div class="metric"><div class="m-icon"><i class="ti ti-transfer"></i></div><div class="m-label">کل ترافیک</div><div class="m-val" id="m-traffic">—<span class="m-unit">MB</span></div></div>',
  '    <div class="metric"><div class="m-icon"><i class="ti ti-folder-check"></i></div><div class="m-label">پروفایل فعال</div><div class="m-val" id="m-active">—</div></div>',
  '    <div class="metric"><div class="m-icon"><i class="ti ti-alert-triangle"></i></div><div class="m-label">خطاها</div><div class="m-val" id="m-errs">—</div></div>',
  '  </div>',
  '  <div class="card"><div class="card-title"><i class="ti ti-chart-area"></i> نمودار ساعتی (MB)</div><div class="chart-box"><canvas id="ch1"></canvas></div></div>',
  '  <div class="card"><div class="card-title"><i class="ti ti-activity"></i> وضعیت سیستم</div>',
  '    <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--card-b);font-size:12px"><span>آپتایم</span><b id="uptime-inline">—</b></div>',
  '    <div style="display:flex;justify-content:space-between;padding:8px 0;font-size:12px"><span>وضعیت</span><span class="badge bg-green"><span class="dot dg"></span> آنلاین</span></div>',
  '  </div>',
  '</section>',
  '<section class="pg" id="pg-items">',
  '  <div class="topbar"><div><div class="tb-title"><i class="ti ti-folders"></i> پروفایل‌ها</div><div class="tb-sub">ساخت و مدیریت پروفایل‌ها</div></div></div>',
  '  <div class="card">',
  '    <div class="card-title"><i class="ti ti-square-rounded-plus"></i> ساخت پروفایل جدید</div>',
  '    <div style="display:flex;flex-wrap:wrap;gap:9px;margin-bottom:12px">',
  '      <input class="fi" id="nl-label" placeholder="عنوان" style="flex:1;min-width:160px">',
  '      <input class="fi" id="nl-val" type="number" min="0" placeholder="سهمیه (0=نامحدود)" style="min-width:130px">',
  '      <select class="fs" id="nl-unit"><option value="GB">GB</option><option value="MB">MB</option></select>',
  '      <input class="fi" id="nl-exp" type="number" min="0" placeholder="انقضا (روز)" style="min-width:120px">',
  '    </div>',
  '    <div style="display:flex;flex-wrap:wrap;gap:9px;margin-bottom:12px">',
  '      <select class="fs" id="nl-proto" style="min-width:160px">',
  '        <option value="ws">WS</option>',
  '        <option value="h2">H2 · auto</option>',
  '      </select>',
  '      <select class="fs" id="nl-fp" style="min-width:170px">',
  '        <option value="chrome">chrome</option>',
  '        <option value="firefox">firefox</option>',
  '        <option value="safari">safari</option>',
  '        <option value="ios">ios</option>',
  '        <option value="android">android</option>',
  '        <option value="edge">edge</option>',
  '        <option value="360">360</option>',
  '        <option value="qq">qq</option>',
  '        <option value="random">random</option>',
  '        <option value="randomized">randomized</option>',
  '        <option value="unsafe">unsafe (بدون جعل TLS)</option>',
  '      </select>',
  '      <input class="fi" id="nl-iplimit" type="number" min="0" placeholder="محدودیت IP" value="0" style="min-width:110px">',
  '      <input class="fi" id="nl-speed" type="number" min="0" placeholder="سرعت Mbps (0=∞)" value="0" style="min-width:140px">',
  '    </div>',
  '    <button class="btn btn-p" onclick="createItem()"><i class="ti ti-plus"></i> ساخت پروفایل</button>',
  '  </div>',
  '  <div class="card"><div class="card-title"><i class="ti ti-list"></i> لیست پروفایل‌ها <span class="badge bg-blue" style="margin-right:auto" id="items-pg-cnt">0</span></div><div id="items-grid"></div></div>',
  '</section>',
  '<section class="pg" id="pg-connections">',
  '  <div class="topbar"><div><div class="tb-title"><i class="ti ti-plug-connected"></i> اتصالات فعال</div></div><button class="btn btn-p btn-sm" onclick="loadConns()"><i class="ti ti-refresh"></i></button></div>',
  '  <div class="card"><div class="card-title"><i class="ti ti-list-details"></i> لیست</div><div id="conns-grid"></div></div>',
  '</section>',
  '<section class="pg" id="pg-logs">',
  '  <div class="topbar"><div><div class="tb-title"><i class="ti ti-history"></i> رویدادها</div></div><button class="btn btn-p btn-sm" onclick="loadLogs()"><i class="ti ti-refresh"></i></button></div>',
  '  <div class="card" id="logs-list"></div>',
  '</section>',
  '<section class="pg" id="pg-errors">',
  '  <div class="topbar"><div><div class="tb-title"><i class="ti ti-alert-triangle"></i> خطاها</div></div></div>',
  '  <div class="card" id="errs-full"></div>',
  '</section>',
  '<section class="pg" id="pg-settings">',
  '  <div class="topbar"><div><div class="tb-title"><i class="ti ti-settings"></i> تنظیمات</div></div></div>',
  '  <div class="card">',
  '    <div class="card-title"><i class="ti ti-key"></i> تغییر رمز عبور</div>',
  '    <div style="display:flex;flex-direction:column;gap:9px;max-width:400px">',
  '      <input class="fi" type="password" id="cp-cur" placeholder="رمز فعلی">',
  '      <input class="fi" type="password" id="cp-new" placeholder="رمز جدید">',
  '      <input class="fi" type="password" id="cp-cf" placeholder="تکرار رمز جدید">',
  '      <button class="btn btn-p" onclick="changePw()"><i class="ti ti-shield-check"></i> ذخیره رمز جدید</button>',
  '    </div>',
  '  </div>',
  '  <div class="card">',
  '    <div class="card-title"><i class="ti ti-info-circle"></i> اطلاعات سیستم</div>',
  '    <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--card-b);font-size:12px"><span>نسخه</span><b>v1.0</b></div>',
  '    <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--card-b);font-size:12px"><span>پلتفرم</span><b>Cloud Worker</b></div>',
  '    <div style="display:flex;justify-content:space-between;padding:8px 0;font-size:12px"><span>ذخیره‌سازی</span><b>KV + Durable Objects</b></div>',
  '  </div>',
  '</section>',
  '</main>',
  '<script>',
  'var isDark = localStorage.getItem("nm-theme") !== "light";',
  'function applyTheme(d) {',
  '  document.documentElement.setAttribute("data-theme", d ? "dark" : "light");',
  '  document.getElementById("theme-icon").className = "ti " + (d ? "ti-sun" : "ti-moon");',
  '  document.getElementById("theme-label").textContent = d ? "تم روشن" : "تم تاریک";',
  '}',
  'function toggleTheme() { isDark = !isDark; localStorage.setItem("nm-theme", isDark ? "dark" : "light"); applyTheme(isDark); }',
  'applyTheme(isDark);',
  'function toast(m, t) {',
  '  var e = document.getElementById("toast");',
  '  e.textContent = m;',
  '  e.className = "toast show" + (t ? " " + t : "");',
  '  setTimeout(function(){ e.classList.remove("show"); }, 2400);',
  '}',
  'function fmtB(b) {',
  '  if (!b || b === 0) return "0 B";',
  '  if (b < 1024) return b + " B";',
  '  if (b < 1024 * 1024) return (b / 1024).toFixed(1) + " KB";',
  '  if (b < 1024 * 1024 * 1024) return (b / 1024 / 1024).toFixed(2) + " MB";',
  '  return (b / 1024 / 1024 / 1024).toFixed(2) + " GB";',
  '}',
  'function toFa(n) { return String(n).replace(/[0-9]/g, function(d){ return "\u06F0\u06F1\u06F2\u06F3\u06F4\u06F5\u06F6\u06F7\u06F8\u06F9"[d]; }); }',
  'function esc(s) { return String(s || "").replace(/[&<>"\']/g, function(c){ var map = { "&":"&amp;", "<":"&lt;", ">":"&gt;", "\\"":"&quot;", "\'":"&#39;" }; return map[c]; }); }',
  'async function authF(url, opts) {',
  '  var r = await fetch(url, opts || {});',
  '  if (r.status === 401) { location.href = "/login"; throw new Error("unauth"); }',
  '  return r;',
  '}',
  'document.getElementById("logout-btn").onclick = async function() {',
  '  await fetch("/api/logout", { method: "POST" });',
  '  location.href = "/login";',
  '};',
  'document.querySelectorAll(".nav-it").forEach(function(el) {',
  '  el.addEventListener("click", function() {',
  '    document.querySelectorAll(".nav-it").forEach(function(n){ n.classList.toggle("on", n.dataset.pg === el.dataset.pg); });',
  '    document.querySelectorAll(".pg").forEach(function(p){ p.classList.toggle("on", p.id === "pg-" + el.dataset.pg); });',
  '    var loaders = { items: loadItems, connections: loadConns, logs: loadLogs, errors: loadErrs };',
  '    var l = loaders[el.dataset.pg];',
  '    if (l) l();',
  '  });',
  '});',
  'var ch1 = null;',
  'async function fetchStats() {',
  '  try {',
  '    var r = await authF("/stats");',
  '    var d = await r.json();',
  '    document.getElementById("m-conns").textContent = d.active_connections;',
  '    document.getElementById("conns-nb").textContent = d.active_connections;',
  '    document.getElementById("m-traffic").innerHTML = (d.total_traffic_mb || 0).toFixed(1) + \'<span class="m-unit">MB</span>\';',
  '    document.getElementById("m-active").textContent = d.active_items || 0;',
  '    document.getElementById("m-errs").textContent = d.total_errors || 0;',
  '    document.getElementById("uptime-inline").textContent = d.uptime;',
  '    document.getElementById("last-upd").textContent = "آخرین بروزرسانی: " + new Date().toLocaleTimeString("fa-IR");',
  '    if (d.hourly && ch1) {',
  '      var labels = Object.keys(d.hourly).sort();',
  '      var vals = labels.map(function(k){ return +(d.hourly[k] / 1024 / 1024).toFixed(2); });',
  '      ch1.data.labels = labels;',
  '      ch1.data.datasets[0].data = vals;',
  '      ch1.update();',
  '    }',
  '    if (d.recent_errors) renderErrs(d.recent_errors);',
  '  } catch (e) {}',
  '}',
  'function renderErrs(errs) {',
  '  var el = document.getElementById("errs-full");',
  '  if (!el) return;',
  '  if (!errs.length) { el.innerHTML = \'<div style="color:var(--green-t);padding:10px;font-size:12px">هیچ خطایی نیست</div>\'; return; }',
  '  el.innerHTML = errs.slice().reverse().map(function(e){',
  '    return \'<div style="padding:9px 0;border-bottom:1px solid var(--card-b)"><div style="color:var(--t3);font-size:10px">\' + new Date(e.time).toLocaleString("fa-IR") + \'</div><div style="color:var(--red-t);font-family:ui-monospace,monospace;background:var(--red-bg);padding:6px 9px;border-radius:6px;word-break:break-all;font-size:10.5px;margin-top:4px">\' + esc(e.error) + \'</div></div>\';',
  '  }).join("");',
  '}',
  'async function loadLogs() {',
  '  try {',
  '    var r = await authF("/api/activity");',
  '    var d = await r.json();',
  '    var logs = (d.logs || []).slice().reverse();',
  '    var el = document.getElementById("logs-list");',
  '    if (!logs.length) { el.innerHTML = \'<div class="empty"><i class="ti ti-history"></i><p>هنوز رویدادی نیست</p></div>\'; return; }',
  '    el.innerHTML = logs.map(function(l){',
  '      return \'<div style="padding:9px 0;border-bottom:1px solid var(--card-b)"><div style="font-size:12.5px">\' + esc(l.message) + \'</div><div style="font-size:10px;color:var(--t3);margin-top:3px">\' + new Date(l.time).toLocaleString("fa-IR") + " \u00B7 " + esc(l.kind) + \'</div></div>\';',
  '    }).join("");',
  '  } catch (e) {}',
  '}',
  'async function loadErrs() {',
  '  var r = await authF("/stats");',
  '  var d = await r.json();',
  '  renderErrs(d.recent_errors || []);',
  '}',
  'var allItems = [];',
  'async function loadItems() {',
  '  try {',
  '    var r = await authF("/api/items");',
  '    var data = await r.json();',
  '    var items = data.items || [];',
  '    allItems = items;',
  '    document.getElementById("items-nb").textContent = items.length;',
  '    document.getElementById("items-pg-cnt").textContent = toFa(items.length);',
  '    var g = document.getElementById("items-grid");',
  '    if (!items.length) { g.innerHTML = \'<div class="empty"><i class="ti ti-folder-off"></i><p>پروفایلی نیست</p></div>\'; return; }',
  '    g.innerHTML = items.map(function(l){',
  '      var pct = l.limit_bytes === 0 ? 0 : Math.min(100, l.used_bytes / l.limit_bytes * 100);',
  '      var bc = pct > 90 ? "var(--red)" : pct > 70 ? "var(--amber)" : "var(--accent)";',
  '      var protoTxt = l.protocol === "h2" ? "H2" : "WS";',
  '      return \'<div class="row-item">\' +',
  '        \'<div style="display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap">\' +',
  '          \'<div style="min-width:0;flex:1">\' +',
  '            \'<div style="font-weight:700;font-size:13px">\' + esc(l.label) + \'</div>\' +',
  '            \'<div style="font-size:10px;color:var(--t3);margin-top:3px">\' +',
  '              \'<span class="mono" data-copy="\' + l.uuid + \'">\' + l.uuid.slice(0,10) + \'\u2026</span>\' +',
  '              " \u00B7 " + protoTxt + " \u00B7 fp: " + esc(l.fingerprint || "chrome") +',
  '            \'</div>\' +',
  '          \'</div>\' +',
  '          \'<button class="btn btn-sm" style="background:var(--accent-d);color:var(--accent2)" data-share="\' + l.share_link + \'"><i class="ti ti-copy"></i></button>\' +',
  '          \'<button class="btn btn-sm" style="background:var(--red-bg);color:var(--red-t)" data-del="\' + l.uuid + \'"><i class="ti ti-trash"></i></button>\' +',
  '        \'</div>\' +',
  '        \'<div class="bar"><div style="width:\' + pct + \'%;background:\' + bc + \'"></div></div>\' +',
  '        \'<div class="ubar-txt"><span>\' + fmtB(l.used_bytes) + \'</span><span>از \' + (l.limit_bytes === 0 ? "\u221E" : fmtB(l.limit_bytes)) + \'</span></div>\' +',
  '      \'</div>\';',
  '    }).join("");',
  '    g.querySelectorAll("[data-copy]").forEach(function(el){ el.onclick = function(){ navigator.clipboard.writeText(el.dataset.copy); toast("کپی شد", "ok"); }; });',
  '    g.querySelectorAll("[data-share]").forEach(function(el){ el.onclick = function(){ navigator.clipboard.writeText(el.dataset.share); toast("کپی شد", "ok"); }; });',
  '    g.querySelectorAll("[data-del]").forEach(function(el){ el.onclick = function(){ delItem(el.dataset.del); }; });',
  '  } catch (e) {}',
  '}',
  'async function createItem() {',
  '  var body = {',
  '    label: document.getElementById("nl-label").value.trim() || "پروفایل جدید",',
  '    limit_value: document.getElementById("nl-val").value || 0,',
  '    limit_unit: document.getElementById("nl-unit").value,',
  '    expires_days: document.getElementById("nl-exp").value || 0,',
  '    protocol: document.getElementById("nl-proto").value,',
  '    fingerprint: document.getElementById("nl-fp").value,',
  '    ip_limit: document.getElementById("nl-iplimit").value || 0,',
  '    speed_limit_value: document.getElementById("nl-speed").value || 0,',
  '    speed_limit_unit: "MBIT"',
  '  };',
  '  try {',
  '    var r = await authF("/api/items", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });',
  '    if (!r.ok) throw new Error();',
  '    ["nl-label","nl-val","nl-exp"].forEach(function(id){ document.getElementById(id).value = ""; });',
  '    toast("پروفایل ساخته شد", "ok");',
  '    loadItems();',
  '  } catch (e) { toast("خطا", "err"); }',
  '}',
  'async function delItem(uid) {',
  '  if (!confirm("حذف شود؟")) return;',
  '  try { await authF("/api/items/" + uid, { method: "DELETE" }); toast("حذف شد", "ok"); loadItems(); } catch (e) { toast("خطا", "err"); }',
  '}',
  'async function loadConns() {',
  '  try {',
  '    var r = await authF("/api/connections");',
  '    var d = await r.json();',
  '    var g = document.getElementById("conns-grid");',
  '    if (!d.configs || !d.configs.length) { g.innerHTML = \'<div class="empty"><i class="ti ti-plug-off"></i><p>اتصالی نیست</p></div>\'; return; }',
  '    g.innerHTML = d.configs.map(function(c){',
  '      var ips = (c.connections || []).map(function(ip){',
  '        return \'<div style="font-size:11px;padding:5px 8px;background:var(--accent-d);border-radius:7px;margin-top:4px;display:flex;justify-content:space-between"><span style="font-family:ui-monospace,monospace">\' + esc(ip.ip) + \'</span><span style="color:var(--t3)">\' + ip.bytes_fmt + \'</span></div>\';',
  '      }).join("");',
  '      return \'<div class="row-item"><div style="font-weight:700;font-size:13px">\' + esc(c.label || c.uuid.slice(0,8)) + \'</div>\' +',
  '        \'<div style="font-size:11px;color:var(--t3);margin-top:4px">\' + toFa(c.ip_count) + " \u0622\u06CC\u200C\u067E\u06CC \u00B7 " + toFa(c.sessions) + " \u0633\u0634\u0646 \u00B7 " + c.bytes_fmt + \'</div>\' +',
  '        \'<div style="margin-top:8px">\' + ips + \'</div></div>\';',
  '    }).join("");',
  '  } catch (e) {}',
  '}',
  'async function changePw() {',
  '  var cur = document.getElementById("cp-cur").value;',
  '  var nw = document.getElementById("cp-new").value;',
  '  var cf = document.getElementById("cp-cf").value;',
  '  if (!cur || !nw || !cf) { toast("همه فیلدها را پر کنید", "err"); return; }',
  '  if (nw !== cf) { toast("تکرار رمز اشتباه", "err"); return; }',
  '  try {',
  '    var r = await authF("/api/change-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ current_password: cur, new_password: nw }) });',
  '    if (!r.ok) { var d = await r.json(); throw new Error(d.detail || "خطا"); }',
  '    toast("رمز تغییر کرد", "ok");',
  '    ["cp-cur","cp-new","cp-cf"].forEach(function(id){ document.getElementById(id).value = ""; });',
  '  } catch (e) { toast(e.message, "err"); }',
  '}',
  'function initCharts() {',
  '  if (!window.Chart) return;',
  '  ch1 = new Chart(document.getElementById("ch1"), {',
  '    type: "line",',
  '    data: { labels: [], datasets: [{ label: "MB", data: [], borderColor: "#8B5CF6", backgroundColor: "rgba(139,92,246,.2)", fill: true, tension: .4, pointRadius: 0, borderWidth: 2.5 }] },',
  '    options: {',
  '      responsive: true, maintainAspectRatio: false,',
  '      plugins: { legend: { display: false } },',
  '      scales: {',
  '        x: { grid: { display: false }, ticks: { color: "#6D4A9E", font: { size: 9 } } },',
  '        y: { grid: { color: "rgba(139,92,246,.06)" }, ticks: { color: "#6D4A9E", font: { size: 9 } } }',
  '      }',
  '    }',
  '  });',
  '}',
  'function refreshAll() {',
  '  fetchStats();',
  '  if (document.getElementById("pg-items").classList.contains("on")) loadItems();',
  '  if (document.getElementById("pg-connections").classList.contains("on")) loadConns();',
  '  toast("رفرش شد", "ok");',
  '}',
  'document.addEventListener("DOMContentLoaded", function() {',
  '  initCharts();',
  '  fetchStats();',
  '  setInterval(fetchStats, 5000);',
  '});',
  '</script>',
  '</body></html>',
].join('\n');
