export const LOGIN_HTML = [
  '<!DOCTYPE html>',
  '<html lang="fa" dir="rtl">',
  '<head>',
  '<meta charset="UTF-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '<title>ورود - login</title>',
  '<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300;400;500;600;700&display=swap" rel="stylesheet">',
  '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.19.0/dist/tabler-icons.min.css">',
  '<style>',
  '*{margin:0;padding:0;box-sizing:border-box}',
  ':root{--bg:#0f081a;--card:rgba(20,10,40,0.92);--accent:#8B5CF6;--text:#F0E8FF;--dim:#6D4A9E;--mid:#A78BFA;--border:rgba(139,92,246,0.25)}',
  'html,body{height:100%;overflow:hidden}',
  'body{font-family:Vazirmatn,sans-serif;background:var(--bg);display:flex;align-items:center;justify-content:center;padding:20px}',
  '.bg{position:fixed;inset:0;background:radial-gradient(ellipse 80% 60% at 50% 0%,rgba(139,92,246,0.15),transparent 70%),var(--bg);z-index:0}',
  '.grid{position:fixed;inset:0;background-image:linear-gradient(rgba(139,92,246,0.05) 1px,transparent 1px),linear-gradient(90deg,rgba(139,92,246,0.05) 1px,transparent 1px);background-size:44px 44px;z-index:0}',
  '.wrap{position:relative;z-index:10;width:100%;max-width:400px}',
  '.card{background:var(--card);border:1px solid var(--border);border-radius:20px;padding:38px 34px 34px;backdrop-filter:blur(24px);box-shadow:0 0 80px rgba(139,92,246,0.1),0 20px 60px rgba(0,0,0,.5)}',
  '.brand{display:flex;align-items:center;gap:14px;margin-bottom:28px}',
  '.brand-icon{width:48px;height:48px;border-radius:50%;background:linear-gradient(135deg,#8B5CF6,#6D28D9);display:flex;align-items:center;justify-content:center;color:#fff;font-size:24px;flex-shrink:0}',
  '.brand-name{font-size:18px;font-weight:700;color:var(--text)}',
  '.brand-sub{font-size:11px;color:var(--dim);margin-top:2px}',
  'h1{font-size:21px;font-weight:700;color:var(--text);margin-bottom:5px}',
  '.sub{font-size:12px;color:var(--mid);margin-bottom:24px;line-height:1.6}',
  '.hint{display:flex;align-items:center;gap:10px;background:rgba(139,92,246,0.08);border:1px solid rgba(139,92,246,0.2);border-radius:10px;padding:10px 14px;margin-bottom:20px}',
  '.hint-label{font-size:11px;color:var(--dim);flex:1}',
  '.hint-val{font-family:ui-monospace,monospace;font-size:14px;font-weight:700;color:var(--accent);background:rgba(139,92,246,0.15);border:1px solid rgba(139,92,246,0.3);padding:3px 11px;border-radius:7px;cursor:pointer}',
  '.field{margin-bottom:18px}',
  '.field label{display:block;font-size:10.5px;font-weight:600;color:var(--dim);margin-bottom:7px;text-transform:uppercase}',
  '.inp-wrap{position:relative}',
  'input[type=password]{width:100%;padding:13px 44px 13px 16px;border-radius:11px;border:1px solid var(--border);background:rgba(0,0,0,.3);color:var(--text);font-family:inherit;font-size:14px;outline:none}',
  '.ic{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:var(--dim);font-size:18px;pointer-events:none}',
  '.err{display:none;background:rgba(239,68,68,.08);border:1px solid rgba(239,68,68,.2);border-radius:10px;padding:10px 14px;margin-bottom:14px;font-size:12px;color:#F87171;align-items:center;gap:8px}',
  '.err.show{display:flex}',
  '.btn{width:100%;padding:13px;border-radius:11px;border:none;cursor:pointer;background:linear-gradient(135deg,#8B5CF6,#6D28D9);color:#fff;font-family:inherit;font-size:14px;font-weight:600;display:flex;align-items:center;justify-content:center;gap:8px}',
  '.footer{margin-top:22px;padding-top:18px;border-top:1px solid var(--border);text-align:center;font-size:10px;color:var(--dim)}',
  '</style>',
  '</head>',
  '<body>',
  '<div class="bg"></div><div class="grid"></div>',
  '<div class="wrap">',
  '<div class="card">',
  '<div class="brand"><div class="brand-icon"><i class="ti ti-cube"></i></div><div><div class="brand-name">Node Manager</div><div class="brand-sub">v1.0</div></div></div>',
  '<h1>ورود</h1>',
  '<p class="sub">برای دسترسی به مدیریت، رمز عبور را وارد کنید</p>',
  '<div class="err" id="err"><i class="ti ti-alert-circle"></i><span id="err-text"></span></div>',
  '<div class="hint"><span class="hint-label">رمز پیش‌فرض</span><span class="hint-val" id="hint-pw">PurplePanel</span></div>',
  '<form id="form">',
  '<div class="field"><label>رمز عبور</label><div class="inp-wrap"><input type="password" id="pw" placeholder="رمز عبور را وارد کنید" autofocus required><i class="ti ti-lock ic"></i></div></div>',
  '<button class="btn" type="submit" id="btn"><i class="ti ti-login-2"></i> ورود</button>',
  '</form>',
  '<div class="footer">Node Manager — Cloud Worker Edition</div>',
  '</div>',
  '</div>',
  '<script>',
  'document.getElementById("hint-pw").addEventListener("click", function(){',
  '  document.getElementById("pw").value = "PurplePanel";',
  '  document.getElementById("pw").focus();',
  '});',
  'document.getElementById("form").addEventListener("submit", async function(e){',
  '  e.preventDefault();',
  '  var btn = document.getElementById("btn");',
  '  var err = document.getElementById("err");',
  '  var et = document.getElementById("err-text");',
  '  err.classList.remove("show");',
  '  btn.disabled = true;',
  '  btn.textContent = "در حال ورود...";',
  '  try {',
  '    var r = await fetch("/api/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password: document.getElementById("pw").value }) });',
  '    if (!r.ok) { var d = await r.json().catch(function(){ return {}; }); throw new Error(d.detail || "خطا"); }',
  '    location.href = "/dashboard";',
  '  } catch (ex) {',
  '    et.textContent = ex.message;',
  '    err.classList.add("show");',
  '    btn.disabled = false;',
  '    btn.textContent = "ورود";',
  '  }',
  '});',
  '</script>',
  '</body></html>',
].join('\n');
