export function getPublicPageHTML(uuidKey) {
  return [
    '<!DOCTYPE html>',
    '<html lang="fa" dir="rtl">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>Node Manager</title>',
    '<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">',
    '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.19.0/dist/tabler-icons.min.css">',
    '<style>',
    '*{margin:0;padding:0;box-sizing:border-box}',
    ':root{--bg:#0f081a;--card:#160c28;--card-b:rgba(139,92,246,0.15);--accent:#8B5CF6;--accent2:#A78BFA;--accent-d:rgba(139,92,246,0.1);--green:#10B981;--green-bg:rgba(16,185,129,0.1);--green-t:#34D399;--t1:#F0E8FF;--t2:#9C8ABF;--t3:#6D4A9E}',
    'html,body{min-height:100%;background:var(--bg);font-family:Vazirmatn,sans-serif;color:var(--t1);font-size:14px}',
    '.wrap{max-width:800px;margin:0 auto;padding:24px 16px 64px}',
    '.brand{display:flex;align-items:center;gap:11px;margin-bottom:24px}',
    '.brand-icon{width:40px;height:40px;border-radius:50%;background:linear-gradient(135deg,#8B5CF6,#6D28D9);display:flex;align-items:center;justify-content:center;color:#fff;font-size:20px}',
    '.brand-name{font-size:14.5px;font-weight:800}',
    '.brand-sub{font-size:9.5px;color:var(--t3)}',
    '.card{background:var(--card);border:1px solid var(--card-b);border-radius:20px;padding:22px;margin-bottom:14px}',
    '.label{font-size:10px;font-weight:700;color:var(--accent2);text-transform:uppercase;letter-spacing:.12em;margin-bottom:8px}',
    '.name{font-size:22px;font-weight:800;margin-bottom:6px}',
    '.sub-url{background:var(--accent-d);border:1px solid var(--card-b);border-radius:12px;padding:11px 13px;font-family:ui-monospace,monospace;font-size:10px;color:var(--accent2);word-break:break-all}',
    '.cfg{background:var(--card);border:1px solid var(--card-b);border-radius:16px;padding:16px;margin-bottom:11px}',
    '.cfg-name{font-size:14px;font-weight:700;margin-bottom:8px}',
    '.bar{height:5px;background:rgba(139,92,246,.1);border-radius:3px;overflow:hidden;margin-bottom:5px}',
    '.bar>div{height:100%;background:var(--green)}',
    '.txt{font-size:10px;color:var(--t3);display:flex;justify-content:space-between}',
    '.btn{background:linear-gradient(135deg,#8B5CF6,#6D28D9);color:#fff;border:none;border-radius:11px;padding:10px 16px;font-family:inherit;font-size:12px;font-weight:700;cursor:pointer;display:inline-flex;align-items:center;gap:5px;margin-top:9px}',
    '.btn-g{background:var(--accent-d);color:var(--accent2)}',
    '.link-box{background:rgba(0,0,0,.22);border:1px solid var(--card-b);border-radius:9px;padding:10px 12px;font-family:ui-monospace,monospace;font-size:9.5px;color:var(--accent2);word-break:break-all;margin-top:9px;max-height:80px;overflow-y:auto}',
    '.toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%) translateY(40px);background:var(--card);border:1px solid var(--card-b);color:var(--t1);border-radius:10px;padding:10px 18px;font-size:12.5px;font-weight:600;opacity:0;transition:all .25s;z-index:999;pointer-events:none}',
    '.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}',
    '.toast.ok{background:var(--green-bg);color:var(--green-t)}',
    '.empty{text-align:center;padding:60px 20px;color:var(--t3)}',
    '</style>',
    '</head>',
    '<body>',
    '<div class="toast" id="toast"></div>',
    '<div class="wrap">',
    '<div class="brand"><div class="brand-icon"><i class="ti ti-cube"></i></div><div><div class="brand-name">Node Manager</div><div class="brand-sub">Subscription</div></div></div>',
    '<div id="root"><div class="empty"><p>در حال بارگذاری...</p></div></div>',
    '</div>',
    '<script>',
    'var UUID_KEY = "' + uuidKey + '";',
    'function toast(m, t) {',
    '  var e = document.getElementById("toast");',
    '  e.textContent = m;',
    '  e.className = "toast show" + (t ? " " + t : "");',
    '  setTimeout(function(){ e.classList.remove("show"); }, 2400);',
    '}',
    'function esc(s) {',
    '  return String(s || "").replace(/[&<>"]/g, function(c) {',
    '    return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\\"": "&quot;" }[c];',
    '  });',
    '}',
    'function fmtB(b) {',
    '  if (!b) return "0 B";',
    '  if (b < 1024) return b + " B";',
    '  if (b < 1024 * 1024) return (b / 1024).toFixed(1) + " KB";',
    '  if (b < 1024 * 1024 * 1024) return (b / 1024 / 1024).toFixed(2) + " MB";',
    '  return (b / 1024 / 1024 / 1024).toFixed(2) + " GB";',
    '}',
    'async function init() {',
    '  try {',
    '    var r = await fetch("/api/public/sub/" + UUID_KEY);',
    '    if (!r.ok) { document.getElementById("root").innerHTML = \'<div class="empty"><p>یافت نشد</p></div>\'; return; }',
    '    var d = await r.json();',
    '    var itemsHtml = (d.items || []).map(function(l) {',
    '      var pct = l.limit_bytes === 0 ? 0 : Math.min(100, l.used_bytes / l.limit_bytes * 100);',
    '      return \'<div class="cfg">\' +',
    '        \'<div class="cfg-name">\' + esc(l.label) + \'</div>\' +',
    '        \'<div class="bar"><div style="width:\' + pct + \'%"></div></div>\' +',
    '        \'<div class="txt"><span>\' + l.used_fmt + \' مصرف</span><span>سهمیه: \' + l.limit_fmt + \'</span></div>\' +',
    '        \'<div class="link-box">\' + esc(l.share_link) + \'</div>\' +',
    '        \'<button class="btn" data-copy="\' + esc(l.share_link) + \'">کپی</button>\' +',
    '        \'<button class="btn btn-g" data-qr="\' + esc(l.share_link) + \'">QR</button>\' +',
    '      \'</div>\';',
    '    }).join("");',
    '    document.getElementById("root").innerHTML =',
    '      \'<div class="card">\' +',
    '        \'<div class="label">گروه</div>\' +',
    '        \'<div class="name">\' + esc(d.name) + \'</div>\' +',
    '        \'<div class="sub-url">\' + esc(d.sub_url) + \'</div>\' +',
    '      \'</div>\' + itemsHtml;',
    '    document.querySelectorAll("[data-copy]").forEach(function(el) {',
    '      el.onclick = function() { navigator.clipboard.writeText(el.dataset.copy); toast("کپی شد", "ok"); };',
    '    });',
    '    document.querySelectorAll("[data-qr]").forEach(function(el) {',
    '      el.onclick = function() { window.open("https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=" + encodeURIComponent(el.dataset.qr), "_blank"); };',
    '    });',
    '  } catch (e) { document.getElementById("root").innerHTML = \'<div class="empty"><p>خطا</p></div>\'; }',
    '}',
    'init();',
    '</script>',
    '</body></html>',
  ].join('\n');
}
