export const DEFAULTS = {
  ADMIN_PASSWORD: 'PurplePanel',
  SESSION_TTL: 60 * 60 * 24 * 365,
  SESSION_COOKIE: 'nm_session',
  RELAY_BUF: 256 * 1024,
  XHTTP_BUF: 512 * 1024,
  TCP_CONNECT_TIMEOUT: 10000,
  DEFAULT_PORT: 443,
  MIN_PORT: 1,
  MAX_PORT: 65535,
  DEFAULT_FINGERPRINT: 'chrome',
  DEFAULT_PROTOCOL: 'ws',
  PROTOCOLS: ['ws', 'h2'],
  FINGERPRINTS: ['chrome', 'firefox', 'safari', 'ios', 'android', 'edge', '360', 'qq', 'random', 'randomized', 'unsafe'],
  DEFAULT_ALPN: { ws: 'http/1.1', h2: 'h2,http/1.1' },
  MIN_RATE: 1024,
  MIN_BURST: 16 * 1024,
  SESSION_IDLE_TIMEOUT: 30,
};
